### ISSUE TITLE
Auto-invoke inference command

### ISSUE THREAD

**Issue by elatoskinas** [saltudelft/type4py-vscode-ext#14]
Inference command should be auto-invoked when using the Type4Py extension. Some possibilities:

* Invoke when file is loaded
* Invoke when file is saved
* Invoke when file is edited (very expensive)
* Poll invoke in-between edits (less expensive than on edits)

**Comment by mir-am** [comment]
For now, the auto-invoke functionality works when a file is opened. (#15 ).
