### ISSUE TITLE
Unit/Integration Tests

### ISSUE THREAD

**Issue by elatoskinas** [saltudelft/type4py-vscode-ext#5]
The extension should be supported by unit and integration tests.

* Find a way to integrate unit tests with the API
* Find a way to mock (?) dependencies/requests
* Write tests for each provider
* Write general test for infer command
* Write tests for error cases in the infer command

**Comment by elatoskinas** [comment]
Good resource (on which the fork origin is based on also): https://code.visualstudio.com/api/working-with-extensions/testing-extension

**Comment by elatoskinas** [comment]
Recommendation to test the following:

* `typestore`
  * `get` query non-existent
  * `add` and `get` query existing
  * `add`, `get`, `add`, `get` to test replacement
* `utils` method: `isWithinLineBounds`
  * In bounds
  * In bounds (first number is on edge)
  * In bounds (second number is on edge)
  * Out of bounds
* `type4pyData`
  * `transformInferApiData` method cases
* `completionProvider`
  * Test `provideCompletionItems` for every provider
* `extension.ts`
  * `infer` function, if possible
  * `active` function?

**Comment by mir-am** [comment]
Addressed in #19.
